In [2]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
path = "/content/drive/MyDrive/Colab Notebooks/Research Energy Consumption Production/Factors.csv"
df = pd.read_csv(path, header=1)
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/Research Energy Consumption Production/Factors.csv'

In [8]:
path = "/C:/Users/Aymane/Desktop/Research/Morocco-Energy-Consumption-Production-Prediction/Factors.csv"
df = pd.read_csv(path, header=1)
df

OSError: [Errno 22] Invalid argument: '/C:/Users/Aymane/Desktop/Research/Morocco-Energy-Consumption-Production-Prediction/Factors.csv'

In [4]:
df.shape

(47, 19)

In [5]:
production = df['Production (TJ)']
consumption = df['Consumption (TJ)']
df1 = df.drop(columns=['Production (TJ)', 'Consumption (TJ)'])
df1.shape

(47, 17)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [7]:
#Data for the Consumption Prediction
X_train, X_test, y_train, y_test = train_test_split(df1, consumption, random_state=47, test_size=0.25)

**Decision Regressor**

In [8]:
tree_model_Consumption = DecisionTreeRegressor(random_state=200)
tree_model_Consumption.fit(X_train,y_train)

DecisionTreeRegressor(random_state=200)

In [9]:
predicted_decision_reg_consumption = tree_model_Consumption.predict(X_test)
predicted_decision_reg_consumption.shape

(12,)

In [10]:
predicted_decision_reg_consumption

array([239954., 431037., 369240., 431037., 199245., 129100., 243601.,
       134900., 314003., 180224., 129100., 202789.])

In [11]:
from sklearn import metrics

tree_model_Consumption.score(X_test, y_test)

0.9678952809062232

**Linear Regression**

In [12]:
Linear_model_Consumption = LinearRegression()
Linear_model_Consumption.fit(X_train, y_train)

LinearRegression()

In [13]:
predicted_Linear_Consumption = Linear_model_Consumption.predict(X_test)
predicted_Linear_Consumption.shape

(12,)

In [14]:
predicted_Linear_Consumption

array([225678.27949457, 379796.07350311, 343200.38704524, 400304.63307478,
       196043.10813691, 125430.98469759, 255966.8994648 , 125744.26968102,
       329649.40605475, 165829.60488745, 126825.5182656 , 213919.42444479])

In [15]:
from sklearn import metrics

Linear_model_Consumption.score(X_test, y_test)
r2_test_lr = r2_score(y_test, prediction_test_lr)
rms_test_lr = sqrt(mean_squared_error(y_test, prediction_test_lr))
mae_test_lr = mean_absolute_error(y_test,prediction_test_lr)
mape_test_lr = np.mean(np.abs((y_test - prediction_test_lr) / y_test)) * 100

# Predicting and Calculating the Metrices for Prediction of Training Dataset
prediction_train_lr = lr.predict(X_train)

r2_train_lr = r2_score(y_train, prediction_train_lr)
rms_train_lr = sqrt(mean_squared_error(y_train, prediction_train_lr))
mae_train_lr = mean_absolute_error(y_train,prediction_train_lr)
mape_train_lr = np.mean(np.abs((y_train - prediction_train_lr) / y_train)) * 100

0.9970100471638305

**Predicting next 15 years**

In [16]:
import numpy as np
years = np.array([2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035])
x_pred = years.reshape(-1, 1)
x_pred

array([[2020],
       [2021],
       [2022],
       [2023],
       [2024],
       [2025],
       [2026],
       [2027],
       [2028],
       [2029],
       [2030],
       [2031],
       [2032],
       [2033],
       [2034],
       [2035]])

In [20]:
## Decision Tree Regression
pred_tree = tree_model_Consumption.predict(X_train)


In [19]:
## Linear Regression
pred_linear = Linear_model_Consumption.predict(X_train)

In [21]:
pred_tree

array([290764., 180224., 124100., 314003., 130700., 503973., 246881.,
       122500., 179870., 103000., 116300., 149962., 123700., 237801.,
        84300.,  96000., 243601., 129100., 436841., 199245., 369240.,
       462740., 449595.,  93800., 239954., 431037., 497157., 443122.,
       202789., 145100., 471364., 124300., 523677., 134900., 134200.])