In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
#path = "/content/drive/MyDrive/Colab Notebooks/Research Energy Consumption Production/Factors.csv"
#df = pd.read_csv(path, header=1)
#df

In [4]:
import numpy as np
import pandas as pd

In [8]:
pd.read_csv?

In [63]:
df = pd.read_csv('Oil Factors.csv', header=1)
df.head()

Years  Production (TJ)  Consumption (TJ)  Transportation (TJ)  \
0   1973             1600             84300                28400   
1   1974             1000             93800                28400   
2   1975              800             96000                30500   
3   1976              400            103000                31900   
4   1977              900            116300                35700   

   Industry  (TJ)  Residential (TJ)  Commercial (TJ)  Population growth (%)  \
0           42900             27200            23000                   2.08   
1           49800             28400            24300                   2.12   
2           46100             29800            26000                   2.18   
3           50400             31800            27700                   2.24   
4           56500             34100            30000                   2.29   

   Population density (%)  GDP (billion USD)  \
0                   24.40              6.242   
1                   24.92              7.675   
2                   25.47              8.985   
3                   26.05              9.584   
4                   26.65             11.050   

   Installed capacity of renewable energies (MW)  Reserves (TJ)  \
0                                            620          612.0   
1                                            620          612.0   
2                                            620          612.0   
3                                            620          612.0   
4                                            620          612.0   

   Oil & products Imports (TJ)  Population growth (%).1  GDP (Trillion USD)  \
0                     102576.6                     1.98               4.642   
1                     126022.7                     1.93               5.350   
2                     128116.1                     1.86               5.960   
3                     136489.7                     1.80               6.479   
4                     149468.8                     1.75               7.328   

   Oil prices ($/MW)  Energy Security (%)  Energy Equity (%)  \
0           5.591059                 -1.0               -1.0   
1          19.679170                 -1.0               -1.0   
2          19.594200                 -1.0               -1.0   
3          21.752450                 -1.0               -1.0   
4          23.655790                 -1.0               -1.0   

   Environmental Sustainability (%)  
0                              -1.0  
1                              -1.0  
2                              -1.0  
3                              -1.0  
4                              -1.0

In [28]:
df.shape

(10, 16)

In [32]:
production = df['Production (TJ)']
consumption = df['Consumption (TJ)']
df1 = df.drop(columns=['Years', 'Production (TJ)', 'Consumption (TJ)'])
df1.shape

(47, 16)

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [34]:
#Data for the Consumption Prediction
X_train, X_test, y_train, y_test = train_test_split(df1, consumption, random_state=47, test_size=0.25)

**Decision Regressor**

In [35]:
tree_model_Consumption = DecisionTreeRegressor(random_state=200)
tree_model_Consumption.fit(X_train,y_train)

DecisionTreeRegressor(random_state=200)

In [36]:
predicted_decision_reg_consumption = tree_model_Consumption.predict(X_test)
predicted_decision_reg_consumption.shape

(12,)

In [37]:
predicted_decision_reg_consumption

array([239954., 369240., 369240., 369240., 199245., 129100., 290764.,
       129100., 314003., 149962., 129100., 202789.])

In [38]:
from sklearn import metrics

tree_model_Consumption.score(X_test, y_test)

0.9634618835451336

**Linear Regression**

In [39]:
Linear_model_Consumption = LinearRegression()
Linear_model_Consumption.fit(X_train, y_train)

LinearRegression()

In [40]:
predicted_Linear_Consumption = Linear_model_Consumption.predict(X_test)
predicted_Linear_Consumption.shape

(12,)

In [41]:
predicted_Linear_Consumption

array([224988.48164832, 377237.87424203, 340093.84966049, 398493.82908384,
       196492.0390639 , 124738.66460538, 255235.80892989, 124423.01042518,
       327664.24489752, 165595.96971729, 126718.31486306, 213077.9721992 ])

In [43]:
from sklearn import metrics

Linear_model_Consumption.score(X_test, y_test)

0.9958017912066518

**Predicting next 15 years**

In [64]:
pred_facts = pd.read_csv('PredOilFactors.csv', index_col=0)
pred_facts

0              1             2              3       0.1  \
0  178869.033302  117854.278446  46255.226642   83752.960222  1.246681   
1  183989.465772  119784.447271  46770.721554   85620.420907  1.216976   
2  189109.898242  121714.616096  47286.216466   87487.881591  1.187271   
3  194230.330712  123644.784921  47801.711378   89355.342276  1.157566   
4  199350.763182  125574.953747  48317.206290   91222.802960  1.127861   
5  204471.195652  127505.122572  48832.701203   93090.263645  1.098156   
6  209591.628122  129435.291397  49348.196115   94957.724329  1.068451   
7  214712.060592  131365.460222  49863.691027   96825.185014  1.038745   
8  219832.493062  133295.629047  50379.185939   98692.645698  1.009040   
9  224952.925532  135225.797872  50894.680851  100560.106383  0.979335   

         1.1         2.1          0.2          1.2            2.2       0.3  \
0  46.813992   84.587487  2102.054810  6605.994255  497809.552798  1.246681   
1  47.407727   87.093682  2158.570883  6663.927766  508964.314928  1.216976   
2  48.001462   89.599876  2215.086957  6721.861277  520119.077058  1.187271   
3  48.595197   92.106070  2271.603030  6779.794787  531273.839188  1.157566   
4  49.188932   94.612265  2328.119103  6837.728298  542428.601318  1.127861   
5  49.782667   97.118459  2384.635176  6895.661809  553583.363448  1.098156   
6  50.376401   99.624654  2441.151249  6953.595319  564738.125578  1.068451   
7  50.970136  102.130848  2497.667322  7011.528830  575892.887708  1.038745   
8  51.563871  104.637042  2554.183395  7069.462340  587047.649838  1.009040   
9  52.157606  107.143237  2610.699468  7127.395851  598202.411968  0.979335   

         1.3         2.3         0.4         1.4         2.4  
0  62.579260  103.830175   87.021112   97.385740   85.691457  
1  64.430572  106.516201   90.241541  101.033430   88.832625  
2  66.281883  109.202227   93.461970  104.681119   91.973793  
3  68.133195  111.888253   96.682399  108.328809   95.114961  
4  69.984507  114.574280   99.902828  111.976499   98.256129  
5  71.835819  117.260306  103.123257  115.624188  101.397296  
6  73.687131  119.946332  106.343686  119.271878  104.538464  
7  75.538443  122.632358  109.564115  122.919568  107.679632  
8  77.389755  125.318384  112.784544  126.567257  110.820800  
9  79.241066  128.004410  116.004973  130.214947  113.961968

In [49]:
pred_facts.shape

(10, 16)

In [60]:
## Decision Tree Regression
pred_tree = tree_model_Consumption.predict(pred_facts)
pred_tree

C:\Users\Aymane\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- 0
- 0.1
- 0.2
- 0.3
- 0.4
- ...
Feature names seen at fit time, yet now missing:
- Commercial (TJ)
- Energy Equity (%)
- Energy Security (%)
- Environmental Sustainability (%)
- GDP (Trillion USD)
- ...

  warnings.warn(message, FutureWarning)


array([369240., 369240., 369240., 369240., 523677., 523677., 523677.,
       523677., 523677., 523677.])

In [59]:
## Linear Regression
pred_linear = Linear_model_Consumption.predict(pred_facts)
pred_linear

C:\Users\Aymane\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- 0
- 0.1
- 0.2
- 0.3
- 0.4
- ...
Feature names seen at fit time, yet now missing:
- Commercial (TJ)
- Energy Equity (%)
- Energy Security (%)
- Environmental Sustainability (%)
- GDP (Trillion USD)
- ...

  warnings.warn(message, FutureWarning)


array([378477.83525077, 388156.69660718, 397835.55796359, 407514.41932   ,
       417193.28067641, 426872.14203282, 436551.00338923, 446229.86474564,
       455908.72610205, 465587.58745846])